import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavigationBar from "@/app/components/NavigationBar";
import { SelectedRowProvider } from "@/app/provider/student-provider"; // Import the context hook
import { CoursesProvider } from "@/app/provider/courses-provider"; // Import the context hook
import { StudentProvider } from "./provider/students-list-provider";

//
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-foreground  bg-custom-gradient`}
      >
        <CoursesProvider>
          <StudentProvider>
            <SelectedRowProvider>
              <NavigationBar />

              {children}
            </SelectedRowProvider>
          </StudentProvider>
        </CoursesProvider>
      </body>
    </html>
  );
}
