# Backend Dockerfile
FROM python:3.12-slim

# Set the working directory
WORKDIR /

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

# Expose the port for the Django app
EXPOSE 8000

# Run migrations and then the Django development server
CMD python manage.py migrate && python manage.py runserver 0.0.0.0:8000
