# Frontend Dockerfile
FROM node:20-alpine

# Set the working directory
WORKDIR /

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port for Next.js
EXPOSE 3000

# Run the Next.js development server
CMD ["npm", "run", "dev"]
